language: csharp
mono: none
dotnet: 2.2
install:
  - nuget restore src/Dommunity.sln
script:
  - dotnet build src/Dommunity.sln
  - dotnet test src/*.Tests
matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode10.1
