language: csharp
mono: none
install:
  - dotnet restore src/Dommunity.sln
script:
  - dotnet build src/Dommunity.sln
  - dotnet test src/*.Tests
matrix:
  include:
    - os: linux
      dist: xenial
      dotnet: 2.2
    - os: osx
      osx_image: xcode10.1
      dotnet: 2.2.100
