language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      before_install:
        - eval "CC=gcc-8 && CXX=g++-8"
    - os: osx
      osx_image: xcode10
script: ./autogen.sh && ./configure && make && make check
