language: csharp
mono: none
install:
  - dotnet restore src/Dommunity.sln
script:
  - dotnet build src/Dommunity.sln
  - for p in src/*.Tests; do echo -e "\033[0;34mRunning tests for $p.\033[0m" && echo && dotnet test $p || exit 1 && echo; done;
matrix:
  include:
    - os: linux
      dist: xenial
      dotnet: 2.2
    - os: osx
      osx_image: xcode10.1
      dotnet: 2.2.100
